
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'






@Entity("MarketGlobalData")
export class MarketGlobalData  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	lastTotalSy: BigInt

	@Required
	@Column("BigInt")
	lastTotalActiveSupply: BigInt

	@Required
	@Column("Int")
	lastUpdatedAt: Int

	@Required
	@Column("BigInt")
	globalIndexEz: BigInt

	@Required
	@Column("BigInt")
	globalIndexEl: BigInt

  constructor(data: Partial<MarketGlobalData>) {}

}

@Entity("MarketAccount")
export class MarketAccount  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	accountIndexEz: BigInt

	@Required
	@Column("BigInt")
	accountIndexEl: BigInt

	@Required
	@Column("BigInt")
	lastActiveBalance: BigInt

  constructor(data: Partial<MarketAccount>) {}

}

@Entity("LiquidLockerGlobData")
export class LiquidLockerGlobData  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	llIndexEz: BigInt

	@Required
	@Column("BigInt")
	llIndexEl: BigInt

	@Required
	@Column("BigInt")
	lastTotalSupply: BigInt

  constructor(data: Partial<LiquidLockerGlobData>) {}

}

@Entity("LiquidLockerAccount")
export class LiquidLockerAccount  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	accountIndexEz: BigInt

	@Required
	@Column("BigInt")
	accountIndexEl: BigInt

	@Required
	@Column("BigInt")
	lastBalance: BigInt

  constructor(data: Partial<LiquidLockerAccount>) {}

}

@Entity("YTAccountSnapshot")
export class YTAccountSnapshot  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("Int")
	lastUpdatedAt: Int

	@Required
	@Column("BigInt")
	lastImpliedHolding: BigInt

  constructor(data: Partial<YTAccountSnapshot>) {}

}

@Entity("AccountPoint")
export class AccountPoint  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	accruedEz: BigInt

	@Required
	@Column("BigInt")
	accruedEl: BigInt

  constructor(data: Partial<AccountPoint>) {}

}


const source = `# type MarketGlobalData = {
#   id: string;
#   lastTotalSy: string;
#   lastTotalActiveSupply: string;
#   lastUpdatedAt: number;
#   globalIndexEz: string;
#   globalIndexEl: string;
# };

# type MarketAccount = {
#   id: string;
#   accountIndexEz: string;
#   accountIndexEl: string;
#   lastActiveBalance: string;
# };

# type LiquidLockerGlobData = {
#   id: string;
#   llIndexEz: string;
#   llIndexEl: string;
#   lastTotalSupply: string;
# };

# type LiquidLockerAccount = {
#   id: string;
#   accountIndexEz: string;
#   accountIndexEl: string;
#   lastBalance: string;
# };

type MarketGlobalData @entity {
  id: ID!
  lastTotalSy: BigInt!
  lastTotalActiveSupply: BigInt!
  lastUpdatedAt: Int!
  globalIndexEz: BigInt!
  globalIndexEl: BigInt!
}

type MarketAccount @entity {
  id: ID!
  accountIndexEz: BigInt!
  accountIndexEl: BigInt!
  lastActiveBalance: BigInt!
}

type LiquidLockerGlobData @entity {
  id: ID!
  llIndexEz: BigInt!
  llIndexEl: BigInt!
  lastTotalSupply: BigInt!
}

type LiquidLockerAccount @entity {
  id: ID!
  accountIndexEz: BigInt!
  accountIndexEl: BigInt!
  lastBalance: BigInt!
}

type YTAccountSnapshot @entity {
  id: ID!
  lastUpdatedAt: Int!
  lastImpliedHolding: BigInt!
}

type AccountPoint @entity {
  id: ID!
  accruedEz: BigInt!
  accruedEl: BigInt!
}`
DatabaseSchema.register({
  source,
  entities: {
    "MarketGlobalData": MarketGlobalData,
		"MarketAccount": MarketAccount,
		"LiquidLockerGlobData": LiquidLockerGlobData,
		"LiquidLockerAccount": LiquidLockerAccount,
		"YTAccountSnapshot": YTAccountSnapshot,
		"AccountPoint": AccountPoint
  }
})
